# Generated by Django 4.1.3 on 2022-11-04 17:23
import csv
from django.db import migrations
import os


def create_db(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Image = apps.get_model('image_api', 'Image')

    filepath = 'image_api/test_application_data.csv'

    with open(os.path.basename(filepath)) as csv_file:
        csv_reader = csv.DictReader(csv_file)

        for row in csv_reader:
            title = row['title']
            image_url = row['image']
            description = row['description']
            image = Image(title=title, image_url=image_url, description=description)

            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_db),
    ]